# Generated by Django 4.2.17 on 2025-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_expense_options_alter_income_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user'], name='finances_ex_user_id_cf7c32_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='finances_ex_categor_19b638_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='finances_ex_date_81e0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user'], name='finances_in_user_id_da5809_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date'], name='finances_in_date_bf3818_idx'),
        ),
    ]
