# Generated by Django 4.2.17 on 2025-01-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_category_options_remove_income_category_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='finances_ex_categor_19b638_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
